name: cs533-bib
channels:
- conda-forge
dependencies:
- python=3.8
- libblas=*=*openblas
- docopt
- pandas>=1.1
- scikit-learn
- scikit-optimize
- notebook
- seaborn
- requests
- html5lib
- tqdm
- dvc